include ".\nums.h"

actors {
    max-actors                                               = 12 when operator is comparison

    indy                                                     = 1
    sophia                                                   = 2
    fish-on-string                                           = 3
    marcus                                                   = 3 when room is [college-office, college-hall, cu-passport] ; brody
    kerner                                                   = 4

    nazi-soldier                                             = 4 when room is [atlantis-maze-ne, atlantis-maze-nw, atlantis-maze-se, atlantis-maze-sw]
    biff                                                     = 5 when room is new-york-street
    heimdall                                                 = 5 when room is iceland-interior
    stagehand                                                = 5 when room is theater-wing
    sub-captain                                              = 5 when room is sub-interior-2
    sophia-in-transit                                        = 5 when room is crete-transit-view
    octopus-1                                                = 5 when room is atl1-canal
    octopus-2                                                = 6 when room is atl1-canal
    octopus-3                                                = 7 when room is atl1-canal
    small-indy-in-desert                                     = 5 when room is desert-over
    sub-corporal-or-bucket                                   = 6 when room is sub-interior-2 ; TODO: both roles played in the same script
    servant                                                  = 6 when room is [algiers-omars-house, algiers-over, algiers-store] ; Paul Abdul
    costa                                                    = 7 when room is azores
    parrot                                                   = 7 when room is yucatan-exterior
    grocer                                                   = 7 when room is algiers-market
    trottier                                                 = 8 when room is [montecarlo-hotel, montecarlo-seance]
    knife-thrower                                            = 8 when room is algiers-market
    balloon-vendor                                           = 9 when room is algiers-roof
    digger                                                   = 9 when room is [digger-top, atl3-bridge-to-god-machine]
    anaconda                                                 = 9 when room is yucatan-exterior
    port-authority                                           = 10 when room is thera-dock
    beggar                                                   = 10 when room is algiers-market
    jungle-rodent                                            = 10 when room is yucatan-exterior
    stranger-1                                               = 11 when room is montecarlo-hotel
    sternhart                                                = 11 when room is [yucatan-exterior, yucatan-interior]
    man-in-red-fez                                           = 11 when room is [algiers-market, algiers-over] ; TODO: in algiers-market, actor 11 also plays the knife...
    labyrinth-gate                                           = 11 when room is labyrinth
    captain                                                  = 11 when room is [thera-dock, salvage-boat]
    nomad                                                    = 11 when room is desert
    stranger-2                                               = 12 when room is montecarlo-hotel
    ubermann                                                 = 12 when room is [nazi-laboratory, atl3-center]
    omar                                                     = 12 when room is [algiers-omars-house, algiers-store]
    sentry-statue                                            = 12 when room is atl1-cageroom
    opponent                                                 = 11 when room is new-york-street and script is global ; Note: this must be before para-street-lamp, or that will take precedence

    ; Nazi guards
    hans                                                     = 5 when room is labyrinth
    rolf                                                     = 5 when room is algiers-dig-exterior
    franz                                                    = 6 when room is [labyrinth, catacombs]
    otto                                                     = 7 when room is labyrinth
    horst                                                    = 7 when room is algiers-omars-house ; actually Hörst
    karl                                                     = 8 when room is catacombs
    kurt                                                     = 9 when room is labyrinth
    anton                                                    = 10 when room is catacombs
    fritz                                                    = 11 when room is atl1-cageroom
    arnold                                                   = 11 when room is catacombs
    klaus                                                    = 12 when room is labyrinth-exterior
    nazi-1                                                   = 5 when room is [atl1-entrance, atl3-center, desert] ; kidnapping Sophia in Atlantis, watch at center, random encounter in desert
    nazi-2                                                   = 6 when room is [atl1-entrance, atl3-center] ; kidnapping Sophia in Atlantis, watch at center

    ; Transportation
    college-car                                              = 5 when room is college-hall
    azores-car                                               = 6 when room is azores
    balloon-on-ground                                        = 7 when room is desert
    balloon                                                  = 8 when room is [desert-over, sea-over]
    compass                                                  = 9 when room is [desert-over, sea-over]
    seaplane                                                 = 9 when room is azores
    crab-raft                                                = 9 when room is atl1-canal
    montecarlo-hotel-car                                     = 9 when room is montecarlo-hotel
    submarine                                                = 11 when room is sea-over
    dromedary-1                                              = 10 when room is desert
    dromedary-2                                              = 12 when room is desert

    ; FX and animation
    fx-actor-1                                               = 9 when room is atl3-center
    fx-actor-2                                               = 10 when room is atl3-center
    fx-actor-3                                               = 11 when room is atl3-center
    title-actor-1                                            = 5 when room is college-attic
    title-actor-2                                            = 6 when room is college-attic
    totem-pole                                               = 5 when room is college-storage
    sparkles                                                 = 7 when room is cu-microtaur
    shattering-glass                                         = 8 when room is college-attic
    explosion-1                                              = 8 when room is nazi-laboratory
    explosion-2                                              = 9 when room is nazi-laboratory
    falling-books                                            = 9 when room is college-catroom
    sun-and-shooting-star                                    = 5 when room is endscene
    smoke                                                    = 9 when room is endscene
    sub-conning-tower-actor                                  = 11 when room is endscene
    microtaur-experiment                                     = 11 when room is nazi-laboratory
    submarine-shadow                                         = 12 when room is endscene
    travel-dot                                               = 10 when room is world-map
    flying-rifle                                             = 10 when room is algiers-dig-exterior
    double-door-chain                                        = 11 when room is atl2-double-door
    nur-ab-sal-spirit                                        = 11 when room is atl2-skeletons
    nur-ab-sal-spirit-vanish                                 = 12 when room is atl2-skeletons
    x-marks-the-spot                                         = 12 when room is crete-ruins-exterior
    ricochet-sparks                                          = 12 when room is [algiers-dig-exterior, algiers-dig-interior]
    falling-rope                                             = 12 when room is algiers-roof
    boiling-water                                            = 12 when room is atl1-2-bot
    stalactite-actor                                         = 12 when room is catacombs
    background-car                                           = 12 when room is new-york-street
    
    roof-fragment                                            = 5 when room is atl3-bridge-to-god-machine

    bronze-gear-actor                                        = 5 when room is atl2-cu-robot-chest-plate
    statue-part-actor                                        = 6 when room is atl2-cu-robot-chest-plate
    bronze-spoked-wheel-actor                                = 7 when room is atl2-cu-robot-chest-plate
    crescent-shaped-gear-actor                               = 8 when room is atl2-cu-robot-chest-plate
    orichalcum-bead-actor                                    = 9 when room is atl2-cu-robot-chest-plate

    ; Parallax effects
    para-rope                                                = 11 when room is algiers-dig-interior
    para-rock                                                = 11 when room is atl1-orichalcum-pool
    para-azores-roof                                         = 11 when room is azores
    para-pillar                                              = 12 when room is atl1-orichalcum-machine
    para-palm-tree                                           = 12 when room is azores
    para-street-lamp                                         = 11 when room is new-york-street
}

costumes {
    indy-suit-skin                                           = 1
    indy-skin                                                = 2
    indy-fight-skin                                          = 3
    biff-fight-skin                                          = 7
    indy-fall-land-skin                                      = 10
    sub-conning-tower-skin                                   = 13
    submarine-shadow-skin                                    = 14
    sun-skin                                                 = 15
    lab-explosion-skin                                       = 16
    compass-skin                                             = 17
    balloon-skin                                             = 18
    sophia-vision-skin                                       = 19 ; well, not really "vision", she's getting a message from Nur-Ab-Sal
    kerner-in-uniform-skin                                   = 20
    marcus-skin                                              = 21
    indy-whip-swing-skin                                     = 26
    indy-climbing-skin                                       = 27
    sophia-skin                                              = 28
    nazi-officer-skin                                        = 29
    nazi-horst-fight-skin                                    = 30
    sub-captain-skin                                         = 32
    sophia-presentation-skin                                 = 34
    microtaur-experiment-skin                                = 35
    ubermann-skin                                            = 36
    stagehand-skin                                           = 37
    presentation-ghost-skin                                  = 38
    seaplane-skin                                            = 39
    costa-skin                                               = 40
    throwing-knife-skin                                      = 42
    captain-skin                                             = 44
    port-authority-skin                                      = 45
    trottier-skin                                            = 46
    biff-skin                                                = 48
    car-crash-explosion-skin                                 = 51
    smoke-pillar-skin                                        = 52
    throw-necklace-in-lava-skin                              = 53
    goldguy-skin                                             = 54
    roof-fragment-skin                                       = 55
    title-skin                                               = 56
    para-rope-skin                                           = 57
    anaconda-skin                                            = 60
    jungle-rodent-skin                                       = 61
    sternhart-skin                                           = 62
    omar-skin                                                = 63
    servant-skin                                             = 64
    trottier-writing-address-skin                            = 66
    grocer-skin                                              = 67
    knife-thrower-skin                                       = 68
    beggar-skin                                              = 69
    parrot-skin                                              = 72
    balloon-vendor-skin                                      = 74
    lucasarts-logo-bend-skin                                 = 75
    falling-rope-skin                                        = 76
    indy-in-ghost-costume-skin                               = 77
    college-car-skin                                         = 78
    submarine-underwater-skin                                = 80
    x-skin                                                   = 81
    submarine-skin                                           = 87
    sentry-walking-skin                                      = 88
    octopus-skin                                             = 89
    small-indy-in-desert-skin                                = 91
    dromedary-skin                                           = 93
    kerner-in-disguise-skin                                  = 94
    man-in-red-fez-skin                                      = 97
    nazi-rolf-skin                                           = 101
    fish-skin                                                = 103
    totem-pole-skin                                          = 109
    flying-rifle-skin                                        = 110
    crab-raft-skin                                           = 112
    robot-parts-skin                                         = 115 ; animating in close-up
    stalactite-skin                                          = 118
    heimdall-skin                                            = 127
    cat-skin                                                 = 128
    male-stranger-skin                                       = 129
    female-stranger-skin                                     = 130
    statue-part-skin                                         = 132 ; animating in close-up
    double-door-chain-skin                                   = 133
    indy-fall-skin                                           = 138
    indy-tumble-skin                                         = 139
    ubermann-excited-skin                                    = 142
    indy-suit-fight-skin                                     = 145
    indy-suit-climbing-skin                                  = 157
    indy-whip-disarm-skin                                    = 158
    nazi-rolf-fight-skin                                     = 161
    nazi-brute-skin                                          = 162
    sparkles-skin                                            = 163
    azores-car-skin                                          = 177
    digger-top-skin                                          = 188
    nur-ab-sal-spirit-skin                                   = 189
    nur-ab-sal-spirit-vanish-skin                            = 190
    mashed-nazi-skin                                         = 194 ; hit by balloon
    balloon-on-ground-skin                                   = 195
    kerner-escape-skin                                       = 197
    indy-recover-skin                                        = 198
    boiling-water-skin                                       = 202
    indy-remove-crumbling-rock-skin                          = 203
    sophia-2-skin                                            = 202 ; fewer chores, otherwise identical?
    background-car-skin                                      = 208
    para-street-lamp-skin                                    = 209
    montecarlo-hotel-car-skin                                = 220
    smoke-skin                                               = 223
    indy-sophia-kiss-skin                                    = 224
    richochet-sparks-skin                                    = 225
    para-rock-skin                                           = 227
    shattering-glass-skin                                    = 230
    para-pillar-skin                                         = 231
    para-palm-tree-skin                                      = 232
    para-azores-roof-skin                                    = 233
    falling-books-skin                                       = 237
    goldguy-glitter-skin                                     = 240
    shooting-star-skin                                       = 242
}