// Variables
47 = First kid (Dave)
48 = Second kid
49 = Third kid
51-54 = Array for Edna's phone number
55-58 = Array for safe combination
76-79 = Array for Meteor Police number
81 = Envelope steamed
82 = Manuscript or cassette in envelope
83 = Envelope stamped
92 = Ed has package
	1 = Kid gave it to him
	2 = Ed got it first
93 = Ed has prints
95 = Death reason
96 = Dying kid
97 = Number of dead kids
104 = Envelope addressed
110 = Game started
111 = Scratchpad for random variables
113 = Kid targeted by Ed
115 = Dave is dead
155 = Prints state
	0 = Initial
	1 = Developed (Good)
	2 = Developed (Bad)
160 = Manuscript state
	0 = Initial
	1 = Revised (Bad)
	2 = Revised (Good)
164 = Telescope position
165 = Shower curtain moving
167 = Victrola is on
169 = Saw alien in telescope
175 = Can't save game

// Bit flag variables
2816 = Lights off
2872 = Always lit (for outside, etc.)
2936 = Kid is Ed's enemy
2960 = Green Tentacle will protect kid from Purple Tentacle
2944 = Kid used Hunk-O-Matic